name: mygarage
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  # core_kit:
  #   path: C:\Users\KmMuzahid\Documents\others\core_kit
  core_kit:
    git:
      url: https://github.com/kmmuzahid/flutter_core_kit.git
      ref: 1.0.11

  cupertino_icons: 
  auto_route: 
  flutter_bloc: 
  get_it: 
  flutter_secure_storage: 
  equatable:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 
  build_runner: 
  auto_route_generator: 
  flutter_launcher_icons: 
  flutter_gen_runner: 
  intl_utils:   # to generate from arb
  flutter_auto_size_text:
  change_app_package_name: 
  pin_code_fields:


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png" # your custom icon path

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
